// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0gYsnQDovhVqj5lvbBYDu7r8jKBbZfqw',
    appId: '1:324869536086:web:c2e36fbb6fd84e4dbefef7',
    messagingSenderId: '324869536086',
    projectId: 'budget-app-6cd36',
    authDomain: 'budget-app-6cd36.firebaseapp.com',
    storageBucket: 'budget-app-6cd36.appspot.com',
    measurementId: 'G-4D0CD6WPPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqzWHuNMFfvGDiPmS7n4-nQjxUZ2qtkVA',
    appId: '1:324869536086:android:77d0f20b7b49b25fbefef7',
    messagingSenderId: '324869536086',
    projectId: 'budget-app-6cd36',
    storageBucket: 'budget-app-6cd36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Oz-zV7wVLuf6mW35o4GiFHBCjfMJXJw',
    appId: '1:324869536086:ios:7c475a55e45dd602befef7',
    messagingSenderId: '324869536086',
    projectId: 'budget-app-6cd36',
    storageBucket: 'budget-app-6cd36.appspot.com',
    iosBundleId: 'com.example.personalBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0gYsnQDovhVqj5lvbBYDu7r8jKBbZfqw',
    appId: '1:324869536086:web:bc8a32bac131697fbefef7',
    messagingSenderId: '324869536086',
    projectId: 'budget-app-6cd36',
    authDomain: 'budget-app-6cd36.firebaseapp.com',
    storageBucket: 'budget-app-6cd36.appspot.com',
    measurementId: 'G-0CS8FFSEW7',
  );
}
